/**********************************************************************************************************************
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *
 *                This software is copyright protected and proprietary to Vector Informatik GmbH.
 *                Vector Informatik GmbH grants to you only those rights as set out in the license conditions.
 *                All other rights remain with Vector Informatik GmbH.
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  TSC_TestLin.h
 *        Config:  SCIM_BP.dpa
 *   ECU-Project:  CIOM
 *
 *     Generator:  MICROSAR RTE Generator Version 4.18.0
 *                 RTE Core Version 1.18.0
 *       License:  Unlimited license CBD1800194 for Volvo Group Trucks Technology
 *
 *   Description:  Header of wrapper software component for Bte-based Rte test cases
 *********************************************************************************************************************/


/** Sender receiver - explicit read services */
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoCCFW_DiagInfoCCFW(DiagInfoCCFW *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoDLFW_DiagInfoDLFW(DiagInfoDLFW *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoELCP1_DiagInfoELCP1(DiagInfoELCP1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoELCP2_DiagInfoELCP2(DiagInfoELCP2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoILCP1_DiagInfoILCP1(DiagInfoILCP1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoILCP2_DiagInfoILCP2(DiagInfoILCP2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoLECM2_DiagInfoLECM2(DiagInfoLECM2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoLECMBasic_DiagInfoLECMBasic(DiagInfoLECMBasic *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoRCECS_DiagInfoRCECS(DiagInfoRCECS *data);
Std_ReturnType TSC_TestLin_Rte_Read_DiagInfoTCP_DiagInfoTCP(DiagInfoTCP *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1DiagInfoL1_FSP1DiagInfoL1(FSP1DiagInfoL1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1DiagInfoL2_FSP1DiagInfoL2(FSP1DiagInfoL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1DiagInfoL3_FSP1DiagInfoL3(FSP1DiagInfoL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1DiagInfoL4_FSP1DiagInfoL4(FSP1DiagInfoL4 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1DiagInfoL5_FSP1DiagInfoL5(FSP1DiagInfoL5 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1ResponseErrorL1_FSP1ResponseErrorL1(FSP1ResponseErrorL1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1ResponseErrorL2_FSP1ResponseErrorL2(FSP1ResponseErrorL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1ResponseErrorL3_FSP1ResponseErrorL3(FSP1ResponseErrorL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1ResponseErrorL4_FSP1ResponseErrorL4(FSP1ResponseErrorL4 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1ResponseErrorL5_FSP1ResponseErrorL5(FSP1ResponseErrorL5 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1SwitchStatusL2_FSP1SwitchStatusL2(FSP1SwitchStatusL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1SwitchStatusL3_FSP1SwitchStatusL3(FSP1SwitchStatusL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1SwitchStatusL4_FSP1SwitchStatusL4(FSP1SwitchStatusL4 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP1SwitchStatusL5_FSP1SwitchStatusL5(FSP1SwitchStatusL5 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2DiagInfoL1_FSP2DiagInfoL1(FSP2DiagInfoL1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2DiagInfoL2_FSP2DiagInfoL2(FSP2DiagInfoL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2DiagInfoL3_FSP2DiagInfoL3(FSP2DiagInfoL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2ResponseErrorL1_FSP2ResponseErrorL1(FSP2ResponseErrorL1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2ResponseErrorL2_FSP2ResponseErrorL2(FSP2ResponseErrorL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2ResponseErrorL3_FSP2ResponseErrorL3(FSP2ResponseErrorL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2SwitchStatusL1_FSP2SwitchStatusL1(FSP2SwitchStatusL1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2SwitchStatusL2_FSP2SwitchStatusL2(FSP2SwitchStatusL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP2SwitchStatusL3_FSP2SwitchStatusL3(FSP2SwitchStatusL3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP3DiagInfoL2_FSP3DiagInfoL2(FSP3DiagInfoL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP3ResponseErrorL2_FSP3ResponseErrorL2(FSP3ResponseErrorL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP3SwitchStatusL2_FSP3SwitchStatusL2(FSP3SwitchStatusL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP4DiagInfoL2_FSP4DiagInfoL2(FSP4DiagInfoL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP4ResponseErrorL2_FSP4ResponseErrorL2(FSP4ResponseErrorL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_FSP4SwitchStatusL2_FSP4SwitchStatusL2(FSP4SwitchStatusL2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_AdjustButtonStatus_LIN_AdjustButtonStatus(LIN_AdjustButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_AlmClkSetCurAlm_rqst_sg_LIN_AlmClkSetCurAlm_rqst_sg(LIN_AlmClkSetCurAlm_rqst_sg *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BackButtonStatus_LIN_BackButtonStatus(LIN_BackButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BackLightDimming_Status_LIN_BackLightDimming_Status(LIN_BackLightDimming_Status *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BlackPanelMode_ButtonStat_LIN_BlackPanelMode_ButtonStat(LIN_BlackPanelMode_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBAudioOnOff_ButtonStat_LIN_BunkBAudioOnOff_ButtonStat(LIN_BunkBAudioOnOff_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBIntLightActvnBtn_stat_LIN_BunkBIntLightActvnBtn_stat(LIN_BunkBIntLightActvnBtn_stat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBParkHeater_ButtonStat_LIN_BunkBParkHeater_ButtonStat(LIN_BunkBParkHeater_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBTempDec_ButtonStat_LIN_BunkBTempDec_ButtonStat(LIN_BunkBTempDec_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBTempInc_ButtonStat_LIN_BunkBTempInc_ButtonStat(LIN_BunkBTempInc_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBVolumeDown_ButtonStat_LIN_BunkBVolumeDown_ButtonStat(LIN_BunkBVolumeDown_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkBVolumeUp_ButtonStat_LIN_BunkBVolumeUp_ButtonStat(LIN_BunkBVolumeUp_ButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2AudioOnOff_ButtonSta_LIN_BunkH2AudioOnOff_ButtonSta(LIN_BunkH2AudioOnOff_ButtonSta *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2Fade_ButtonStatus_LIN_BunkH2Fade_ButtonStatus(LIN_BunkH2Fade_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2IntLightActvnBtn_sta_LIN_BunkH2IntLightActvnBtn_sta(LIN_BunkH2IntLightActvnBtn_sta *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2IntLightDecBtn_stat_LIN_BunkH2IntLightDecBtn_stat(LIN_BunkH2IntLightDecBtn_stat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2IntLightIncBtn_stat_LIN_BunkH2IntLightIncBtn_stat(LIN_BunkH2IntLightIncBtn_stat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2LockButtonStatus_LIN_BunkH2LockButtonStatus(LIN_BunkH2LockButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2OnOFF_ButtonStatus_LIN_BunkH2OnOFF_ButtonStatus(LIN_BunkH2OnOFF_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2PHTi_rqs_sg_LIN_BunkH2PHTi_rqs_sg(LIN_BunkH2PHTi_rqs_sg *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2ParkHeater_ButtonSta_LIN_BunkH2ParkHeater_ButtonSta(LIN_BunkH2ParkHeater_ButtonSta *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2Phone_ButtonStatus_LIN_BunkH2Phone_ButtonStatus(LIN_BunkH2Phone_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2PowerWinCloseDSBtn_s_LIN_BunkH2PowerWinCloseDSBtn_s(LIN_BunkH2PowerWinCloseDSBtn_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2PowerWinClosePSBtn_s_LIN_BunkH2PowerWinClosePSBtn_s(LIN_BunkH2PowerWinClosePSBtn_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2PowerWinOpenDSBtn_st_LIN_BunkH2PowerWinOpenDSBtn_st(LIN_BunkH2PowerWinOpenDSBtn_st *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2PowerWinOpenPSBtn_st_LIN_BunkH2PowerWinOpenPSBtn_st(LIN_BunkH2PowerWinOpenPSBtn_st *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2RoofhatchCloseBtn_St_LIN_BunkH2RoofhatchCloseBtn_St(LIN_BunkH2RoofhatchCloseBtn_St *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2RoofhatchOpenBtn_Sta_LIN_BunkH2RoofhatchOpenBtn_Sta(LIN_BunkH2RoofhatchOpenBtn_Sta *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2TempDec_ButtonStatus_LIN_BunkH2TempDec_ButtonStatus(LIN_BunkH2TempDec_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2TempInc_ButtonStatus_LIN_BunkH2TempInc_ButtonStatus(LIN_BunkH2TempInc_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2VolumeDown_ButtonSta_LIN_BunkH2VolumeDown_ButtonSta(LIN_BunkH2VolumeDown_ButtonSta *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_BunkH2VolumeUp_ButtonStatu_LIN_BunkH2VolumeUp_ButtonStatu(LIN_BunkH2VolumeUp_ButtonStatu *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_DRL_ButtonStatus_LIN_DRL_ButtonStatus(LIN_DRL_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_DifflockDeactivationBtn_st_LIN_DifflockDeactivationBtn_st(LIN_DifflockDeactivationBtn_st *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_DifflockMode_Wheelstatus_LIN_DifflockMode_Wheelstatus(LIN_DifflockMode_Wheelstatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_DoorAutoFuncBtn_stat_LIN_DoorAutoFuncBtn_stat(LIN_DoorAutoFuncBtn_stat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_EscButtonMuddySiteStatus_LIN_EscButtonMuddySiteStatus(LIN_EscButtonMuddySiteStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_FCWPushButton_LIN_FCWPushButton(LIN_FCWPushButton *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_FogLightFront_ButtonStat_1_LIN_FogLightFront_ButtonStat_1(LIN_FogLightFront_ButtonStat_1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_FogLightFront_ButtonStat_2_LIN_FogLightFront_ButtonStat_2(LIN_FogLightFront_ButtonStat_2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_FogLightRear_ButtonStat_1_LIN_FogLightRear_ButtonStat_1(LIN_FogLightRear_ButtonStat_1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_FogLightRear_ButtonStat_2_LIN_FogLightRear_ButtonStat_2(LIN_FogLightRear_ButtonStat_2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_HeadLampUpDown_SwitchStatu_LIN_HeadLampUpDown_SwitchStatu(LIN_HeadLampUpDown_SwitchStatu *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtCenterBtnFreeWhl_s_LIN_IntLghtCenterBtnFreeWhl_s(LIN_IntLghtCenterBtnFreeWhl_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtDimmingLvlDecBtn_s_LIN_IntLghtDimmingLvlDecBtn_s(LIN_IntLghtDimmingLvlDecBtn_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtDimmingLvlFreeWhl_s_LIN_IntLghtDimmingLvlFreeWhl_s(LIN_IntLghtDimmingLvlFreeWhl_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtDimmingLvlIncBtn_s_LIN_IntLghtDimmingLvlIncBtn_s(LIN_IntLghtDimmingLvlIncBtn_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtMaxModeBtnPnl2_s_LIN_IntLghtMaxModeBtnPnl2_s(LIN_IntLghtMaxModeBtnPnl2_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtModeSelrFreeWheel_s_LIN_IntLghtModeSelrFreeWheel_s(LIN_IntLghtModeSelrFreeWheel_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtNightModeBt2_s_LIN_IntLghtNightModeBt2_s(LIN_IntLghtNightModeBt2_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_IntLghtRestModeBtnPnl2_s_LIN_IntLghtRestModeBtnPnl2_s(LIN_IntLghtRestModeBtnPnl2_s *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_LKSPushButton_LIN_LKSPushButton(LIN_LKSPushButton *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_LevelingThumbwheel_stat_LIN_LevelingThumbwheel_stat(LIN_LevelingThumbwheel_stat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_LightMode_Status_1_LIN_LightMode_Status_1(LIN_LightMode_Status_1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_LightMode_Status_2_LIN_LightMode_Status_2(LIN_LightMode_Status_2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_MemButtonStatus_LIN_MemButtonStatus(LIN_MemButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_Offroad_ButtonStatus_LIN_Offroad_ButtonStatus(LIN_Offroad_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_RearWorkProjector_BtnStat_LIN_RearWorkProjector_BtnStat(LIN_RearWorkProjector_BtnStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_SelectButtonStatus_LIN_SelectButtonStatus(LIN_SelectButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_SpeedControlModeButtonStat_LIN_SpeedControlModeButtonStat(LIN_SpeedControlModeButtonStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_SpeedControlModeWheelStat_LIN_SpeedControlModeWheelStat(LIN_SpeedControlModeWheelStat *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_StopButtonStatus_LIN_StopButtonStatus(LIN_StopButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_TCP_ABS_ButtonStatus_LIN_TCP_ABS_ButtonStatus(LIN_TCP_ABS_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_TCP_ATC_ButtonStatus_LIN_TCP_ATC_ButtonStatus(LIN_TCP_ATC_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_TCP_ESC_ButtonStatus_LIN_TCP_ESC_ButtonStatus(LIN_TCP_ESC_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_TCP_KnobPostionStatus_LIN_TCP_KnobPostionStatus(LIN_TCP_KnobPostionStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_TCP_TCS_ButtonStatus_LIN_TCP_TCS_ButtonStatus(LIN_TCP_TCS_ButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_WRDownButtonStatus_LIN_WRDownButtonStatus(LIN_WRDownButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_LIN_WRUpButtonStatus_LIN_WRUpButtonStatus(LIN_WRUpButtonStatus *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorCCFW_ResponseErrorCCFW(ResponseErrorCCFW *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorDLFW_ResponseErrorDLFW(ResponseErrorDLFW *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorELCP1_ResponseErrorELCP1(ResponseErrorELCP1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorELCP2_ResponseErrorELCP2(ResponseErrorELCP2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorILCP1_ResponseErrorILCP1(ResponseErrorILCP1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorILCP2_ResponseErrorILCP2(ResponseErrorILCP2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorLECM2_ResponseErrorLECM2(ResponseErrorLECM2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorLECMBasic_ResponseErrorLECMBasic(ResponseErrorLECMBasic *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorRCECS_ResponseErrorRCECS(ResponseErrorRCECS *data);
Std_ReturnType TSC_TestLin_Rte_Read_ResponseErrorTCP_ResponseErrorTCP(ResponseErrorTCP *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded1L1_SwitchDetectionNeeded1L1(SwitchDetectionNeeded1L1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded1L2_SwitchDetectionNeeded1L2(SwitchDetectionNeeded1L2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded1L3_SwitchDetectionNeeded1L3(SwitchDetectionNeeded1L3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded1L4_SwitchDetectionNeeded1L4(SwitchDetectionNeeded1L4 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded1L5_SwitchDetectionNeeded1L5(SwitchDetectionNeeded1L5 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded2L1_SwitchDetectionNeeded2L1(SwitchDetectionNeeded2L1 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded2L2_SwitchDetectionNeeded2L2(SwitchDetectionNeeded2L2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded2L3_SwitchDetectionNeeded2L3(SwitchDetectionNeeded2L3 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded3L2_SwitchDetectionNeeded3L2(SwitchDetectionNeeded3L2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionNeeded4L2_SwitchDetectionNeeded4L2(SwitchDetectionNeeded4L2 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp1L1_SwitchDetectionResp1L1(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp1L2_SwitchDetectionResp1L2(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp1L3_SwitchDetectionResp1L3(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp1L4_SwitchDetectionResp1L4(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp1L5_SwitchDetectionResp1L5(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp2L1_SwitchDetectionResp2L1(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp2L2_SwitchDetectionResp2L2(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp2L3_SwitchDetectionResp2L3(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp3L2_SwitchDetectionResp3L2(uint8 *data);
Std_ReturnType TSC_TestLin_Rte_Read_SwitchDetectionResp4L2_SwitchDetectionResp4L2(uint8 *data);

/** Sender receiver - explicit write services */
Std_ReturnType TSC_TestLin_Rte_Write_ABS_Indication_ABS_Indication(ABS_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_ATC_Indication_ATC_Indication(ATC_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_BswM_SRI_BswM_MSI_BswMRteMDG_LIN1Schedule_BswM_MDGP_BswMRteMDG_LIN1Schedule_requestedMode(BswM_BswMRteMDG_LIN1Schedule data);
Std_ReturnType TSC_TestLin_Rte_Write_BswM_SRI_BswM_MSI_BswMRteMDG_LIN2Schedule_BswM_MDGP_BswMRteMDG_LIN2Schedule_requestedMode(BswM_BswMRteMDG_LIN2Schedule data);
Std_ReturnType TSC_TestLin_Rte_Write_BswM_SRI_BswM_MSI_BswMRteMDG_LIN3Schedule_BswM_MDGP_BswMRteMDG_LIN3Schedule_requestedMode(BswM_BswMRteMDG_LIN3Schedule data);
Std_ReturnType TSC_TestLin_Rte_Write_BswM_SRI_BswM_MSI_BswMRteMDG_LIN4Schedule_BswM_MDGP_BswMRteMDG_LIN4Schedule_requestedMode(BswM_BswMRteMDG_LIN4Schedule data);
Std_ReturnType TSC_TestLin_Rte_Write_BswM_SRI_BswM_MSI_BswMRteMDG_LIN5Schedule_BswM_MDGP_BswMRteMDG_LIN5Schedule_requestedMode(BswM_BswMRteMDG_LIN5Schedule data);
Std_ReturnType TSC_TestLin_Rte_Write_DoorLock_stat_DoorLock_stat(DoorLock_stat data);
Std_ReturnType TSC_TestLin_Rte_Write_ESC_Indication_ESC_Indication(ESC_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP1IndicationCmdL2_FSP1IndicationCmdL2(FSP1IndicationCmdL2 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP1IndicationCmdL3_FSP1IndicationCmdL3(FSP1IndicationCmdL3 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP1IndicationCmdL4_FSP1IndicationCmdL4(FSP1IndicationCmdL4 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP1IndicationCmdL5_FSP1IndicationCmdL5(FSP1IndicationCmdL5 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP2IndicationCmdL1_FSP2IndicationCmdL1(FSP2IndicationCmdL1 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP2IndicationCmdL2_FSP2IndicationCmdL2(FSP2IndicationCmdL2 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP2IndicationCmdL3_FSP2IndicationCmdL3(FSP2IndicationCmdL3 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP3IndicationCmdL2_FSP3IndicationCmdL2(FSP3IndicationCmdL2 data);
Std_ReturnType TSC_TestLin_Rte_Write_FSP4IndicationCmdL2_FSP4IndicationCmdL2(FSP4IndicationCmdL2 data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_ACCOrCCIndication_LIN_ACCOrCCIndication(LIN_ACCOrCCIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_ASLIndication_LIN_ASLIndication(LIN_ASLIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_Adjust_DeviceIndication_LIN_Adjust_DeviceIndication(LIN_Adjust_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_AlmClkCurAlarm_stat_sg_LIN_AlmClkCurAlarm_stat_sg(const LIN_AlmClkCurAlarm_stat_sg *data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_AudioSystemStatus_LIN_AudioSystemStatus(LIN_AudioSystemStatus data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_AudioVolumeIndicationCmd_LIN_AudioVolumeIndicationCmd(LIN_AudioVolumeIndicationCmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_BTStatus_LIN_BTStatus(LIN_BTStatus data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_DaytimeRunningLight_Indica_LIN_DaytimeRunningLight_Indica(LIN_DaytimeRunningLight_Indica data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_DifflockOnOff_Indication_LIN_DifflockOnOff_Indication(LIN_DifflockOnOff_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_DoorAutoFuncInd_cmd_LIN_DoorAutoFuncInd_cmd(LIN_DoorAutoFuncInd_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_Down_DeviceIndication_LIN_Down_DeviceIndication(LIN_Down_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_DrivingLightPlus_Indicatio_LIN_DrivingLightPlus_Indicatio(LIN_DrivingLightPlus_Indicatio data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_DrivingLight_Indication_LIN_DrivingLight_Indication(LIN_DrivingLight_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_EscButtonMuddySiteDeviceIn_LIN_EscButtonMuddySiteDeviceIn(LIN_EscButtonMuddySiteDeviceIn data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_FCW_DeviceIndication_LIN_FCW_DeviceIndication(LIN_FCW_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_FrontFog_Indication_LIN_FrontFog_Indication(LIN_FrontFog_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLghtLvlIndScaled_cmd_LIN_IntLghtLvlIndScaled_cmd(LIN_IntLghtLvlIndScaled_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLghtModeInd_cmd_sg_LIN_IntLghtModeInd_cmd_sg(const LIN_IntLghtModeInd_cmd_sg *data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLghtOffModeInd_cmd_LIN_IntLghtOffModeInd_cmd(LIN_IntLghtOffModeInd_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLightMaxModeInd_cmd_LIN_IntLightMaxModeInd_cmd(LIN_IntLightMaxModeInd_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLightNightModeInd_cmd_LIN_IntLightNightModeInd_cmd(LIN_IntLightNightModeInd_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_IntLightRestingModeInd_cmd_LIN_IntLightRestingModeInd_cmd(LIN_IntLightRestingModeInd_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_LKS_DeviceIndication_LIN_LKS_DeviceIndication(LIN_LKS_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_M1_DeviceIndication_LIN_M1_DeviceIndication(LIN_M1_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_M2_DeviceIndication_LIN_M2_DeviceIndication(LIN_M2_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_M3_DeviceIndication_LIN_M3_DeviceIndication(LIN_M3_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_Offroad_Indication_LIN_Offroad_Indication(LIN_Offroad_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_ParkingLight_Indication_LIN_ParkingLight_Indication(LIN_ParkingLight_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_PhoneButtonIndication_cmd_LIN_PhoneButtonIndication_cmd(LIN_PhoneButtonIndication_cmd data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_RearFog_Indication_LIN_RearFog_Indication(LIN_RearFog_Indication data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_RearWorkProjector_Indicati_LIN_RearWorkProjector_Indicati(LIN_RearWorkProjector_Indicati data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_ShortPulseMaxLength_LIN_ShortPulseMaxLength(LIN_ShortPulseMaxLength data);
Std_ReturnType TSC_TestLin_Rte_Write_LIN_Up_DeviceIndication_LIN_Up_DeviceIndication(LIN_Up_DeviceIndication data);
Std_ReturnType TSC_TestLin_Rte_Write_TCS_Indication_TCS_Indication(TCS_Indication data);




