#######################################################################################################################
# File Name  : Makefile.config                                                                                        #
# Description: This makefile contains the target specific project settings (will be included by Makefile)             #
# Project    : Vector Basic Runtime System                                                                            #
# Module     : BrsHw for platform Freescale/ST MPC57xx                                                                #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# COPYRIGHT                                                                                                           #
#---------------------------------------------------------------------------------------------------------------------#
# Copyright (c) 2018 by Vector Informatik GmbH.                                                  All rights reserved. #
#                                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# AUTHOR IDENTITY                                                                                                     #
#---------------------------------------------------------------------------------------------------------------------#
# Name                          Initials      Company                                                                 #
# ----------------------------  ------------  ------------------------------------------------------------------------#
# Benjamin Walter               visbwa        Vector Informatik GmbH                                                  #
# Jens Haerer                   visjhr        Vector Informatik GmbH                                                  #
# Michael Tiran                 vismin        Vector Informatik GmbH                                                  #
# Sascha Mauser                 vismaa        Vector Infromatik GmbH                                                  #
# Ivo Georgiev                  visivg        Vector Infromatik GmbH                                                  #
#---------------------------------------------------------------------------------------------------------------------#
# REVISION HISTORY                                                                                                    #
#---------------------------------------------------------------------------------------------------------------------#
# Version   Date        Author  Description                                                                           #
# --------  ----------  ------  --------------------------------------------------------------------------------------#
# 01.00.00  2015-05-05  visbwa  New creation, based on zBrs_Mpc@root[3.09.04],                                        #
#                               according to template for BrsHw Codestyle 2.0                                         #
# 01.00.01  2015-12-09  visjhr  Added support for VEBN01473                                                           #
# 01.00.02  2016-01-13  visbwa  Added FLOAT_SUPPORT and OBJECT_FORMAT (moved here from DiabData Makefile)             #
# 01.00.03  2016-03-23  vismin  Added support for VEBN01655                                                           #
# 01.01.00  2016-07-01  visbwa  Adapted complete file header structure for zBrs_Template@root[2.00.02]                #
# 01.01.01  2016-10-21  vismaa  Added support for HSR165 (Quasar2e)                                                   #
# 01.01.02  2017-02-08  visbwa  Added Os_CoreGen7 support                                                             #
# 01.01.03  2017-06-28  visivg  Added support for SPC574Kx_144PIN and S32R274_257BALL, removed VEBN01387              #
# 01.01.04  2018-03-27  vismaa  Review according to Brs_Template 2.02.01                                              #
#######################################################################################################################

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Derivative (see BrsHw_DerivativeList.h for supported ones)
# This is used for ROM/RAM mapping, compiler switches, etc...
#------------------------------------------------------------------------------
DERIVATIVE = MPC5746C

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select clock frequency of main oscillator (MHz)
#------------------------------------------------------------------------------
MAIN_OSC_CLK = 40

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select BRS time base clock (MHz). PLL will be used to create this frequency.
# Possible values are:  Derivative specific
#------------------------------------------------------------------------------
TIMEBASE_CLOCK = 160

#------------------------------------------------------------------------------
#------------------------- Must be filled out ---------------------------------
# Select length encoding
# possible values are: BOOKE, VLE
#------------------------------------------------------------------------------
LENGTH_ENCODING = VLE

#------------------------------------------------------------------------------
#-------------------- Must be filled out for DiabData compiler ----------------
# Select Object Module Format
# possible values are:
#      E  -  ELF EABI Object Format (standard)
#      D  -  COFF Object Format
#      F  -  No Small-Data ELF EABI Object Format
#      L  -  ELF EABI little-endian Object Format
#      M  -  No Small-Data ELF EABI little-endian Object Format
#------------------------------------------------------------------------------
OBJECT_FORMAT = E

#-------------------- Must be filled out for DiabData compiler ----------------
# Select Floating Point Support
# possible values are:
#      N  -  No Floating Point (standard)
#      H  -  Hardware Floating Point
#      S  -  Software Floating Point
#      F  -  Single Hardware, Double Software Floating Point
#      G  -  All Single Hardware Floating Point
#      V  -  Vector Floating Point
#------------------------------------------------------------------------------
FLOAT_SUPPORT = S

#------------------------------------------------------------------------------
#--------------- Must be filled out if BRS_ENABLE_SUPPORT_LEDS is set ---------
# Select EVA board, possible values are:
#      DEFAULT         -  Value of BRSHW_LED_PORT_NUMBER is used
#      VEBN01335       -  MPC5747C customer ECU -> no LED support, set STB/EN for CAN0+1
#      VEBN01357       -  PC583003 (Quasar3) -> no LED, set FR_A + LIN pins
#      VEBN01473       -  PC580020 (Quasar2)
#      VEBN01655       -  PC580000 (Quasar0)
#      HSR165          -  PC582101 (Quasar2e)
#      SPC574Kx_144PIN -  SPC574KADPT144S on SPC57xxMB 
#                           (toggle Port A Pin 0 --> LED2)
#      S32R274_257BALL -  S32R274RRU EVB on MCP57xxMB
#------------------------------------------------------------------------------
EVA_BOARD = DEFAULT

#------------------------- Can be filled out ----------------------------------
# Select the type of used OS.
# Possible values are: BRS      Timer/IRQ generated by BRS (Default)
#                      OSGEN7   Os_CoreGen7 based MICROSAR OS
#------------------------------------------------------------------------------
OS_USECASE = OSGEN7
